//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 01:57:02 PM EDT 
//


package ca.polymtl.jaxb.schema.odem;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.polymtl.jaxb.schema.odem package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.polymtl.jaxb.schema.odem
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ODEM.Header }
     * 
     */
    public ODEM.Header createODEMHeader() {
        return new ODEM.Header();
    }

    /**
     * Create an instance of {@link ODEM.Context.Container.Namespace }
     * 
     */
    public ODEM.Context.Container.Namespace createODEMContextContainerNamespace() {
        return new ODEM.Context.Container.Namespace();
    }

    /**
     * Create an instance of {@link ODEM.Header.CreatedBy }
     * 
     */
    public ODEM.Header.CreatedBy createODEMHeaderCreatedBy() {
        return new ODEM.Header.CreatedBy();
    }

    /**
     * Create an instance of {@link ODEM.Header.CreatedBy.Exporter }
     * 
     */
    public ODEM.Header.CreatedBy.Exporter createODEMHeaderCreatedByExporter() {
        return new ODEM.Header.CreatedBy.Exporter();
    }

    /**
     * Create an instance of {@link ODEM.Context.Container }
     * 
     */
    public ODEM.Context.Container createODEMContextContainer() {
        return new ODEM.Context.Container();
    }

    /**
     * Create an instance of {@link ODEM.Context.Container.Namespace.Type.Dependencies }
     * 
     */
    public ODEM.Context.Container.Namespace.Type.Dependencies createODEMContextContainerNamespaceTypeDependencies() {
        return new ODEM.Context.Container.Namespace.Type.Dependencies();
    }

    /**
     * Create an instance of {@link ODEM.Context.Container.Namespace.Type.Dependencies.DependsOn }
     * 
     */
    public ODEM.Context.Container.Namespace.Type.Dependencies.DependsOn createODEMContextContainerNamespaceTypeDependenciesDependsOn() {
        return new ODEM.Context.Container.Namespace.Type.Dependencies.DependsOn();
    }

    /**
     * Create an instance of {@link ODEM }
     * 
     */
    public ODEM createODEM() {
        return new ODEM();
    }

    /**
     * Create an instance of {@link ODEM.Context }
     * 
     */
    public ODEM.Context createODEMContext() {
        return new ODEM.Context();
    }

    /**
     * Create an instance of {@link ODEM.Context.Container.Namespace.Type }
     * 
     */
    public ODEM.Context.Container.Namespace.Type createODEMContextContainerNamespaceType() {
        return new ODEM.Context.Container.Namespace.Type();
    }

}
